### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by s18924** [ffalcinelli/jdivert#6]
Hi,
got this stackTrace when tried to run program that use JDivert on a fresh windows 10.
Is there any setup that needs to be done before actually running JDivert?
Program runs on another "old" machine. 

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\S\AppData\Local\Temp\jna-83\jna3912429470763720517.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
	at com.sun.jna.Native.<clinit>(Native.java:140)
	at com.github.ffalcinelli.jdivert.windivert.DeployHandler.deploy(DeployHandler.java:117)
	at com.github.ffalcinelli.jdivert.windivert.DeployHandler.deploy(DeployHandler.java:97)
	at com.github.ffalcinelli.jdivert.windivert.WinDivertDLL.<clinit>(WinDivertDLL.java:36)
	at com.github.ffalcinelli.jdivert.WinDivert.<init>(WinDivert.java:43)
	at com.github.ffalcinelli.jdivert.WinDivert.<init>(WinDivert.java:58)
	at Test.main(Test.java:24)

**Comment by linxi-1214** [comment]
Same Error! Any idea?

**Comment by ffalcinelli** [comment]
As the library is deeply changed, I'm going to close this issue as obsolete
